config/routes.rb
Rails.application.routes.draw do
  mount BetterMailerPreviews::Engine, at: "/mailers" if Rails.env.development?
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_for :users, controllers: {invitations: "admin/invitations"}

  get "dashboard" => "pages#dashboard", :as => :pages_dashboard

  namespace :admin do
    resources :users
  end

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2, maximum: 50}, uniqueness: true
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Devise::InvitationsController
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      flash[:notice] = "Usuário Convidado"
      render turbo_stream: turbo_stream.action(:redirect, admin_users_path)
    else
      render "devise/invitations/new", status: :unprocessable_entity
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action -> { @sidebar = "users" }
  before_action :set_user, only: %i[edit update destroy]
  include Pagy::Backend

  def index
    @users = policy_scope(User).order("unaccent(lower(name)) ASC")
    if params[:search].present?
      @users = @users.where("unaccent(lower(name)) LIKE ?", "%#{params[:search].downcase}%")
    end
    @pagy, @users = pagy(@users)
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      flash[:notice] = "Usuário Cadastrado"
      render turbo_stream: turbo_stream.action(:redirect, admin_users_path)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    # Filtra os parâmetros para verificar se o password está presente
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      flash[:notice] = "Usuário Atualizado"
      render turbo_stream: turbo_stream.action(:redirect, admin_users_path)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "Usuário Excluído!"
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  default_form_builder TailwindBuilder

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar esta ação."
    redirect_to(root_path)
  end

  protected

  def after_sign_in_path_for(resource)
    pages_dashboard_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:invite, keys: [:name])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    redirect_to pages_dashboard_path if user_signed_in?
  end

  def dashboard
    @sidebar = "dashboard"
  end
end

app/helpers/admin/invitations_helper.rb
module Admin::InvitationsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tailwind_builder.rb
# frozen_string_literal: true

class TailwindBuilder < ViewComponent::Form::Builder
  namespace "TailwindForm"

  # Não gerar divs com a classe field_with_errors
  ActionView::Base.field_error_proc = proc { |html_tag, instance| html_tag.html_safe }

  def switch_field(method, options = {})
    render_component(:switch, @object_name, method, true, false, objectify_options(options))
  end

  def flatpickr_field(method, options = {})
    render_component(:flatpickr, @object_name, method, objectify_options(options))
  end

  def search_field(method, options = {})
    render_component(:search_field, @object_name, method, objectify_options(options))
  end
end

app/views/admin/users/_form.html.erb
<%= form_with model: user, url: @user.new_record? ? admin_users_path : admin_user_path(@user), html: { class: "space-y-6" } do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <% if @user.persisted? %>
      <em class="text-sm text-gray-500">Deixar em branco para manter a senha atual</em>
    <% end %>
  </div>
  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<li class="relative flex justify-between gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
  <div class="flex min-w-0 gap-x-4">
    <svg class="size-12 text-gray-500 flex-none rounded-full" fill="none" viewBox="0 0 24 24" stroke-width="1.0" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
    </svg>
    <div class="min-w-0 flex-auto">
      <p class="text-sm/6 font-semibold text-gray-900">
        <%= link_to edit_admin_user_path(user), data: {turbo_frame: 'drawer-frame'} do %>
          <span class="absolute inset-x-0 -top-px bottom-0"></span>
          <%= user.name %>
          <% if user.admin? %>
            <span class="inline-flex items-center gap-x-1.5 rounded-full bg-yellow-100 px-1.5 py-0.5 text-xs font-medium text-yellow-700">
              Admin
            </span>
          <% end %>
        <% end %>
      </p>
      <p class="mt-1 flex text-xs/5 text-gray-500">
        <%= user.email %>
      </p>
    </div>
  </div>
  <div class="flex shrink-0 items-center gap-x-4">
    <div class="hidden sm:flex sm:flex-col sm:items-end">
      <p class="text-sm/6 text-gray-900"></p>
      <p class="mt-1 text-xs/5 text-gray-500">Created <%= local_time_ago(user.created_at) %></p>
    </div>
    <svg class="size-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
      <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
    </svg>
  </div>
</li>

app/views/admin/users/edit.html.erb
<%= render DrawerComponent.new(title: "Editar Usuário", animate: @user.errors.none?) do %>
  <%= render 'form', user: @user %>
  <% if policy(@user).destroy? %>
    <div class="mt-6 overflow-hidden rounded-lg bg-gray-200 shadow">
      <div class="px-4 py-5 sm:px-6 font-bold">
        Apagar usuário
      </div>
      <div class="bg-white px-4 py-5 sm:p-6">
        <p class="text-red-500 text-xs pb-6">O usuário e todas as suas operações serão apagadas. Não é possível reverter esta ação.</p>
        <%= link_to "Excluir Usuário #{@user.name}",
            admin_user_path(@user),
            data: {turbo_method: :delete, turbo_confirm: 'Excluir o usuário. Tem certeza?', turbo_frame: '_top'},
            class: "flex w-full justify-center rounded-md bg-red-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/users/index.html.erb
<div class="border-b border-gray-200 bg-white px-4 pb-3 sm:px-6 mb-3">
  <h3 class="text-base font-semibold text-gray-900">Lista de usuários</h3>
</div>
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <%= form_with url: admin_users_path, class:"max-w-sm", method: :get do |f| %>
        <%= f.search_field :search, value: params[:search], placeholder: "Search users..." %>
      <% end %>
    </div>
    <div class="flex gap-x-4">
      <%= link_to "Novo", new_admin_user_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: {turbo_frame: 'drawer-frame'}%>
      <%= link_to "Convidar", new_user_invitation_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: {turbo_frame: 'drawer-frame'}%>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
          <%= render @users %>
        </ul>
        <%= render PagyComponent.new(pagy: @pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render DrawerComponent.new(title: "Novo Usuário", animate: @user.errors.none?) do %>
  <%= render 'form', user: @user %>
<% end %>

app/views/layouts/_flashes.html.erb
<% return unless notice || alert %>
<% stimulus = {
  controller: "notification",
  notification_delay_value: 4000,
  transition_enter_from: "opacity-0 translate-y-6",
  transition_enter_to: "opacity-100 translate-y-0",
  transition_leave_from: "opacity-100 translate-y-0",
  transition_leave_to: "opacity-0 translate-y-6"
} %>
<% alert_classes = "bg-red-50 text-red-800" %>
<% notice_classes = "bg-green-50 text-green-800" %>
<% button_classes = alert ? "bg-red-50 hover:bg-red-100 text-red-500" : "bg-green-50 hover:bg-green-100 text-green-500" %>
<%= content_tag :div, data: stimulus, class: "fixed inset-x-0 bottom-4 mx-auto transition transform duration-1000 hidden rounded-md p-4 w-max #{alert ? alert_classes : notice_classes}" do %>
  <div class="flex">
    <div class="flex-shrink-0">
      <% if alert %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
        </svg>
      <% else %>
        <svg class="h-5 w-5 #{alert ? 'text-red-400' : 'text-green-400'}" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </div>
    <div class="ml-3">
      <p class="text-sm font-medium">
        <%= notice || alert %>
      </p>
    </div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button data-action="notification#hide" type="button" class="inline-flex rounded-md p-1.5 focus:outline-none focus:ring-2 focus:ring-offset-2 #{button_classes}">
          <span class="sr-only">Dismiss</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
          </svg>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div data-controller="sidebar">
  <%# -------------------------- %>
  <%# ----- MOBILE SIDEBAR ----- %>
  <%# -------------------------- %>
  <div class="relative z-40 hidden" role="dialog" aria-modal="true" data-sidebar-target="container">
    <div class="fixed inset-0 bg-gray-900/80" aria-hidden="true" data-sidebar-target="backdrop"
      data-sidebar-target="backdrop"
      data-transition-enter="ease-in-out duration-500"
      data-transition-enter-start="opacity-0"
      data-transition-enter-end="opacity-100"
      data-transition-leave="ease-in-out duration-500"
      data-transition-leave-start="opacity-100"
      data-transition-leave-end="opacity-0"></div>
    <div class="fixed inset-0 flex">
      <div class="relative mr-16 flex w-full max-w-xs flex-1"
        data-sidebar-target="panel"
        data-transition-enter="transition ease-in-out duration-300 transform"
        data-transition-enter-start="-translate-x-full"
        data-transition-enter-end="translate-x-0"
        data-transition-leave="transition ease-in-out duration-300 transform"
        data-transition-leave-start="translate-x-0"
        data-transition-leave-end="-translate-x-full">
        <div class="absolute left-full top-0 flex w-16 justify-center pt-5">
          <button type="button" class="-m-2.5 p-2.5"
            data-sidebar-target="close"
            data-action="click->sidebar#close"
            data-transition-enter="ease-in-out duration-300"
            data-transition-enter-start="opacity-0"
            data-transition-enter-end="opacity-100"
            data-transition-leave="ease-in-out duration-300"
            data-transition-leave-start="opacity-100"
            data-transition-leave-end="opacity-0">
            <span class="sr-only">Close sidebar</span>
            <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-100 px-6 pb-2">
          <%= render 'layouts/sidebar_content' %>
        </div>
      </div>
    </div>
  </div>
  <%# --------------------------- %>
  <%# ----- DESKTOP SIDEBAR ----- %>
  <%# --------------------------- %>
  <div class="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
    <div class="flex grow flex-col gap-y-5 overflow-y-auto border-r border-gray-200 bg-gray-100 px-6">
      <%= render 'layouts/sidebar_content' %>
    </div>
  </div>
  <%# ------------------------- %>
  <%# ----- HEADER MOBILE ----- %>
  <%# ------------------------- %>
  <div class="sticky top-0 z-30 flex items-center gap-x-6 bg-gray-100 px-4 py-4 shadow-sm sm:px-6 lg:hidden">
    <button type="button" class="-m-2.5 p-2.5 text-gray-700 lg:hidden" data-action="click->sidebar#open">
      <span class="sr-only">Open sidebar</span>
      <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>
    </button>
    <div class="flex-1 text-sm font-semibold leading-6 text-gray-900">App Name</div>
  </div>
</div>

app/views/layouts/_sidebar_content.html.erb
<%
  base = "group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6"
  current = "bg-gray-50 text-indigo-600"
  default = "text-gray-700 hover:text-indigo-600 hover:bg-gray-50"
%>
<div class="flex h-16 shrink-0 items-center">
  <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
</div>
<nav class="flex flex-1 flex-col">
  <ul role="list" class="flex flex-1 flex-col gap-y-7">
    <li>
      <ul role="list" class="-mx-2 space-y-1">
        <li>
          <%= render SidebarLinkComponent.new(
            path: pages_dashboard_path,
            icon: :home,
            title: "Dashboard",
            selected: @sidebar == "dashboard") %>
        </li>
        <li>
          <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
            </svg>
            Page 1
          </a>
        </li>
        <li>
          <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Page 2
          </a>
        </li>
      </ul>
    </li>
    <% if current_user.admin? %>
      <li>
        <div class="text-xs font-semibold leading-6 text-gray-400">
          Ações do Administrador
        </div>
        <ul role="list" class="-mx-2 mt-2 space-y-1">
          <li>
            <%= render SidebarLinkComponent.new(
                path: admin_users_path,
                icon: :users,
                title: "Usuários",
                selected: @sidebar == "users") %>
          </li>
        </ul>
      </li>
    <% end %>
    <li class="-mx-6 mt-auto text-left">
      <div data-controller="reveal">
        <button data-action="click->reveal#toggle" class="inline-flex w-full items-center text-left gap-x-4 px-6 py-3 text-sm font-semibold leading-6 text-gray-900 hover:bg-gray-50">
          <span class="inline-block h-8 w-8 overflow-hidden rounded-full bg-gray-100">
            <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
              <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
          </span>
          <div class="ml-3">
            <p class="text-sm font-medium text-gray-700 group-hover:text-gray-900">
              <%= current_user.name.truncate(80) %>
            </p>
            <p class="text-xs font-medium text-gray-500 group-hover:text-gray-700">
              <%= current_user.email.truncate(80)%>
            </p>
          </div>
          <div class="ml-auto">
            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-4 w-4 text-gray-400">
              <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 15.75 7.5-7.5 7.5 7.5" />
            </svg>
          </div>
        </button>
        <div data-reveal-target="item" class="hidden absolute z-10 w-3/4 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none bottom-16 left-16" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
          <div class="py-1" role="none">
            <%= link_to edit_user_registration_path, class: "group flex items-center px-4 py-2 text-sm text-gray-700" do %>
              <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
              </svg>
              Editar Conta
            <% end %>
          </div>
          <div class="py-1" role="none">
            <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "group flex items-center px-4 py-2 text-sm text-gray-700" do %>
              <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
              </svg>
              Sair
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>BoilerplateRails</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body class="h-full">
    <%= turbo_frame_tag "drawer-frame" %>
    <%= render "layouts/flashes" %>
    <% if user_signed_in? %>
      <%= render "layouts/sidebar" %>
      <main class="py-10 lg:pl-72">
        <div class="px-4 sm:px-6 lg:px-8">
          <%= yield %>
        </div>
      </main>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/lookbook.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>BoilerplateRails</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body style="padding: 60px">
    <div style="margin-left: auto; margin-right: auto; max-width: <%= params[:lookbook][:display][:max_width] || "100%" %>">
      <%= yield %> <!-- rendered preview will be injected here -->
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

app/views/pages/home.html.erb
<div class="relative isolate px-6 pt-14 lg:px-8">
  <div class="absolute inset-0 -z-10 transform-gpu overflow-hidden blur-3xl" aria-hidden="true">
    <div class="relative left-1/2 top-1/2 h-full w-full -translate-x-1/2 -translate-y-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
  <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
    <div class="mb-8 flex justify-center">
      <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
        Texto de anúncio <a href="#" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span>Saiba mais <span aria-hidden="true">&rarr;</span></a>
      </div>
    </div>
    <div class="text-center">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Rails Boilerplate</h1>
      <p class="mt-6 text-lg leading-8 text-gray-600">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
      <div class="mt-10 flex items-center justify-center gap-x-6">
        <%= link_to "Entrar", new_user_session_path, class: "rounded-md bg-indigo-600 px-20 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    </div>
  </div>
</div>